import Animals

MyChicken = Animals.Chicken("Sally", 2)
print(MyChicken)
MyChicken.SetAge(MyChicken.GetAge() + 1)
print(MyChicken)
MyChicken.SetType("Gorilla")
print(MyChicken)
MyChicken.MakeSound()
print(MyChicken.GetName())
Caterpillar = Animals.Animal("Fuzz", 1, "Caterpillar")
print(Caterpillar)
Caterpillar.SetType("Butterfly")
print(Caterpillar)
print(Caterpillar.GetType())
MyDog = Animals.Dog()
print(MyDog)
MyDog.SetName("Charlee")
print(MyDog.GetName())
MyDog.MakeSound()
